name: Node CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.13.0]
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Installing dependencies
      working-directory: ./frontend
      run: |
        npm ci
    - name: Running linting and style checking
      working-directory: ./frontend
      run: |
        npm run lint
    - name: Running typechecking
      working-directory: ./frontend
      run: |
        npm run typecheck
    - name: Running unit Tests and Validating Coverage
      working-directory: ./frontend
      run: |
        npm run test:ci
    - name: modifying environment var
      run: |
        GITHUB_WORKSPACE=/home/runner/work/solo/solo/frontend
    - name: Run Snyk to check for vulnerabilities
      uses: snyk/actions/node@master
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        CI: true
